import { Inter } from "next/font/google";
import Head from 'next/head';
import "../pages/globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Projects from "@/components/Projects";
import WobbleCardDemo from "@/components/Wobble";
import Footer from "@/components/Footer";
import Contact from "@/components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <title>Jaya Sai Srikar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${inter.className} bg-black`}>
        <Navbar />
        <div className="py-20"><Contact /></div>
        <Footer />
        {children}
      </div>
    </>
  );
}
